x=int(input("enter your first nummber:"))
y=int(input("enter your second nummber:"))
print("add",x+y)
print("substract",x-y)
print("multiple",x*y)
print("divide",x/y)
print("int divition",x//y)
print("reminder",x%y)
print("power",x**y)
