x = int(input("enter your first number:"))
y = int(input("enter your second number:"))
print("add", x + y)
print("subtract", x - y)
print("multiple", x * y)
print("divide", x / y)
print("int division", x // y)
print("reminder", x % y)
print("power", x ** y)
